export const BRISBANE_SUBURBS = [
  "Acacia Ridge",
  "Albion",
  "Alderley",
  "Algester",
  "Annerley",
  "Anstead",
  "Archerfield",
  "Ascot",
  "Ashgrove",
  "Aspley",
  "Auchenflower",
  "Bald Hills",
  "Balmoral",
  "Banyo",
  "Bardon",
  "Bellbowrie",
  "Belmont",
  "Berrinba",
  "Boondall",
  "Bowen Hills",
  "Bracken Ridge",
  "Bridgeman Downs",
  "Brighton",
  "Brisbane City",
  "Brookfield",
  "Bulimba",
  "Burbank",
  "Calamvale",
  "Camp Hill",
  "Cannon Hill",
  "Capalaba West",
  "Carina",
  "Carina Heights",
  "Carindale",
  "Carseldine",
  "Chandler",
  "Chapel Hill",
  "Chelmer",
  "Chermside",
  "Chermside West",
  "Chuwar",
  "City",
  "Clayfield",
  "Coopers Plains",
  "Coorparoo",
  "Corinda",
  "Darra",
  "Deagon",
  "Doolandella",
  "Drewvale",
  "Durack",
  "Dutton Park",
  "Eagle Farm",
  "East Brisbane",
  "Eight Mile Plains",
  "Ellen Grove",
  "Enoggera",
  "Enoggera Reservoir",
  "Everton Park",
  "Fairfield",
  "Ferny Grove",
  "Fig Tree Pocket",
  "Fitzgibbon",
  "Forest Lake",
  "Fortitude Valley",
  "Gaythorne",
  "Geebung",
  "Gordon Park",
  "Graceville",
  "Grange",
  "Greenslopes",
  "Gumdale",
  "Hamilton",
  "Hawthorne",
  "Heathwood",
  "Hemmant",
  "Hendra",
  "Herston",
  "Highgate Hill",
  "Holland Park",
  "Holland Park West",
  "Inala",
  "Indooroopilly",
  "Jamboree Heights",
  "Jindalee",
  "Kangaroo Point",
  "Karawatha",
  "Kedron",
  "Kelvin Grove",
  "Kenmore",
  "Kenmore Hills",
  "Keperra",
  "Kholo",
  "Kuraby",
  "Lota",
  "Lutwyche",
  "Lytton",
  "MacGregor",
  "Mackenzie",
  "Manly",
  "Manly West",
  "Mansfield",
  "McDowall",
  "Middle Park",
  "Milton",
  "Mitchelton",
  "Moggill",
  "Moorooka",
  "Morningside",
  "Mt Coot-tha",
  "Mt Crosby",
  "Mt Gravatt",
  "Mt Gravatt East",
  "Mt Ommaney",
  "Murarrie",
  "Nathan",
  "New Farm",
  "Newmarket",
  "Newstead",
  "Norman Park",
  "Northgate",
  "Nudgee",
  "Nudgee Beach",
  "Nundah",
  "Oxley",
  "Paddington",
  "Pallara",
  "Parkinson",
  "Payne Road",
  "Petrie Terrace",
  "Pinjarra Hills",
  "Pinkenba",
  "Port of Brisbane",
  "Pullenvale",
  "Ransome",
  "Red Hill",
  "Richlands",
  "Riverhills",
  "Robertson",
  "Rochedale",
  "Rocklea",
  "Runcorn",
  "Salisbury",
  "Sandgate",
  "Seven Hills",
  "Seventeen Mile Rocks",
  "Sherwood",
  "Shorncliffe",
  "Sinnamon Park",
  "South Brisbane",
  "Spring Hill",
  "St Lucia",
  "Stafford",
  "Stafford Heights",
  "Stretton",
  "Sumner",
  "Sunnybank",
  "Sunnybank Hills",
  "Taigum",
  "Taringa",
  "Tarragindi",
  "Teneriffe",
  "Tennyson",
  "The Gap",
  "Tingalpa",
  "Toowong",
  "Upper Brookfield",
  "Upper Kedron",
  "Upper Mt Gravatt",
  "Virginia",
  "Wacol",
  "Wakerley",
  "Wavell Heights",
  "Wayamba",
  "West End",
  "Westlake",
  "Willawong",
  "Windsor",
  "Wishart",
  "Woolloongabba",
  "Wooloowin",
  "Wynnum",
  "Wynnum West",
  "Yeerongpilly",
  "Yeronga",
  "Zillmere"
];
